# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GClO764rFzCWh9FVd_O_o6Dn4UeIliVe
"""

!pip install ultralytics

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

results = model.train(data="/content/dataset_colab.yaml", epochs=20)

results = model.val()

!pip install onnx
!pip install onnxruntime-gpu onnxslim

import onnx
success = model.export(format="onnx")

from google.colab import files
files.download("/content/runs/detect/train3/weights/best.onnx")

from google.colab import files
files.download("/content/runs/detect/train3/weights/best.pt")

import cv2
from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/best.pt")

image_path = "/content/samp.jpeg"
results = model.predict(image_path)

image = cv2.imread(image_path)

for result in results:
    for box in result.boxes:
        x1, y1, x2, y2 = map(int, box.xyxy[0])
        confidence = box.conf[0].item()
        class_id = int(box.cls[0].item())
        label = f"Class {class_id}: {confidence:.2f}"

        print(f"Detected Class {class_id} - Coordinates: ({x1}, {y1}), ({x2}, {y2})")

        cv2.rectangle(image, (x1, y1), (x2, y2), (0, 255, 0), 2)
        cv2.putText(image, label, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

print(f"Total objects detected: {len(results[0].boxes)}")

# cv2.imshow("Predictions", image)
cv2.waitKey(0)
cv2.destroyAllWindows()